# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_qr_scan_array <- function(grayarray, w, h, debug = FALSE) {
    .Call(`_quadrangle_rcpp_qr_scan_array`, grayarray, w, h, debug)
}

