# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Scan a grayscale array using the quirc C++ engine
#' 
#' Should only be called from quadrangle::qr_scan_cpp in R
#' 
#' @param grayarray Vector of grayscale pixel values
#' @param w Width of pixel array
#' @param h Height of pixel array
#' @param debug Return additional info about found QR codes (ECC level, version, etc)
rcpp_qr_scan_array <- function(grayarray, w, h, debug = FALSE) {
    .Call(`_quadrangle_rcpp_qr_scan_array`, grayarray, w, h, debug)
}

